name: Backend CI/CD Pipeline - abhiabhishektr
on:
  push:
    paths:
      - 'Backend/**'
  pull_request:
    paths:
      - 'Backend/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'

    - name: Check PR target branch
      if: github.event_name == 'pull_request'
      run: |
        if [[ "${{ github.base_ref }}" != "develop" ]]; then
          echo "This PR is targeting a branch other than 'develop'."
          exit 1
        fi

    # Step to ensure .env, node_modules, and dist folders are not committed
    - name: Check for restricted files/folders
      run: |
        if find Backend -name ".env" -print -quit | grep -q .; then
          echo "Error: .env file(s) found in the Backend directory or its subdirectories."
          exit 1
        fi
        if find Backend -name "node_modules" -type d -print -quit | grep -q .; then
          echo "Error: node_modules directory found in the Backend directory or its subdirectories."
          exit 1
        fi
        if find Backend -name "dist" -type d -print -quit | grep -q .; then
          echo "Error: dist directory found in the Backend directory or its subdirectories."
          exit 1
        fi

    - name: Install dependencies
      run: |
        cd Backend
        npm install

    - name: Build TypeScript
      run: |
        cd Backend
        npm run build

    # Step to auto-close the PR if the build fails
    - name: Close PR on Failure
      if: failure() && github.event_name == 'pull_request'
      run: |
        curl -X PATCH \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d '{"state": "closed"}' \
        https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
